### ISSUE TITLE
error: 'zone.js:484 Unhandled Promise rejection: Zone.assertZonePatched is not a function' after upgrading to 2.0.0

### ISSUE THREAD

**Issue by kolkov** [ui-router/quickstart-ng2#18]
![image](https://cloud.githubusercontent.com/assets/3740898/18596772/900d706c-7c53-11e6-83c8-01279979c0c4.png)

![image](https://cloud.githubusercontent.com/assets/3740898/18596791/a176d0a0-7c53-11e6-99fd-d12c650878d2.png)

**Comment by ericmartinezr** [comment]
That's because of your zone,js version, you should be on zone.js 0.6.2x, you're on an older one

**Comment by kolkov** [comment]
@ericmartinezr Thanks! This fixed, but has another errors from ui-router-ng2...
https://github.com/angular-ui/ui-router/issues/3007

**Comment by christopherthielen** [comment]
so this can be closed?
