### ISSUE TITLE
Beta.3?

### ISSUE THREAD

**Issue by Waitak** [ui-router/quickstart-ng2#16]
npm install can't find ui-router-ng2@1.0.0-beta.3,

> npm ERR! No compatible version found: ui-router-ng2@^1.0.0-beta.3
> npm ERR! Valid install targets:
> npm ERR! 1.0.0-beta.2, 1.0.0-beta.1, 1.0.0-alpha.5, 1.0.0-alpha.4, 1.0.0-alpha.3, 1.0.0-alpha.2, 0.1.0-preview.0

and npm tsc fails to compile with ui-router-ng2@1.0.0-beta.2.

> node_modules/ui-router-ng2/ng2/uiRouterNgModule.d.ts(3,10): error TS2305: Module '"/home/scott/Doozee/Web/rates2/node_modules/@angular/core/index"' has no exported member 'NgModuleMetadataType'.
> src/app.module.ts(25,3): error TS2345: Argument of type '{ imports: typeof BrowserModule[]; providers: ((TypeProvider | ValueProvider | ClassProvider | Ex...' is not assignable to parameter of type 'UIRouterModuleMetadata'.
>   Object literal may only specify known properties, and 'imports' does not exist in type 'UIRouterModuleMetadata'.
> src/bar/bar.module.ts(7,3): error TS2345: Argument of type '{ imports: typeof SharedModule[]; states: Ng2StateDeclaration[]; }' is not assignable to parameter of type 'UIRouterModuleMetadata'.
>   Object literal may only specify known properties, and 'imports' does not exist in type 'UIRouterModuleMetadata'.
> src/baz/baz.module.ts(7,3): error TS2345: Argument of type '{ imports: typeof SharedModule[]; states: Ng2StateDeclaration[]; }' is not assignable to parameter of type 'UIRouterModuleMetadata'.
>   Object literal may only specify known properties, and 'imports' does not exist in type 'UIRouterModuleMetadata'.
> src/foo/foo.module.ts(7,3): error TS2345: Argument of type '{ imports: typeof SharedModule[]; states: Ng2StateDeclaration[]; }' is not assignable to parameter of type 'UIRouterModuleMetadata'.
>   Object literal may only specify known properties, and 'imports' does not exist in type 'UIRouterModuleMetadata'.

Where do we find ui-router-ng2@1.0.0-beta.3?

**Comment by christopherthielen** [comment]
oh sorry, my bad.  I didn't mean to push that commit

**Comment by Waitak** [comment]
Ah, that makes sense. Thanks for the reply.
